top100 = [
    "youtube.com",
    "en.wikipedia.org",
    "facebook.com",
    "twitter.com",
    "amazon.com",
    "imdb.com",
    "reddit.com",
    "pinterest.com",
    "ebay.com",
    "tripadvisor.com",
    "craigslist.org",
    "walmart.com",
    "instagram.com",
    "google.com",
    "nytimes.com",
    "apple.com",
    "linkedin.com",
    "indeed.com",
    "play.google.com",
    "espn.com",
    "webmd.com",
    "cnn.com",
    "homedepot.com",
    "etsy.com",
    "netflix.com",
    "quora.com",
    "microsoft.com",
    "target.com",
    "merriam-webster.com",
    "forbes.com",
    "mapquest.com",
    "nih.gov",
    "gamepedia.com",
    "yahoo.com",
    "healthline.com",
    "foxnews.com",
    "allrecipes.com",
    "quizlet.com",
    "weather.com",
    "bestbuy.com",
    "urbandictionary.com",
    "mayoclinic.org",
    "aol.com",
    "genius.com",
    "zillow.com",
    "usatoday.com",
    "glassdoor.com",
    "msn.com",
    "rottentomatoes.com",
    "lowes.com",
    "dictionary.com",
    "businessinsider.com",
    "usnews.com",
    "medicalnewstoday.com",
    "britannica.com",
    "washingtonpost.com",
    "usps.com",
    "finance.yahoo.com",
    "irs.gov",
    "yellowpages.com",
    "chase.com",
    "retailmenot.com",
    "accuweather.com",
    "wayfair.com",
    "go.com",
    "live.com",
    "login.yahoo.com",
    "steamcommunity.com",
    "xfinity.com",
    "cnet.com",
    "ign.com",
    "steampowered.com",
    "macys.com",
    "wikihow.com",
    "mail.yahoo.com",
    "wiktionary.org",
    "cbssports.com",
    "cnbc.com",
    "bankofamerica.com",
    "expedia.com",
    "wellsfargo.com",
    "groupon.com",
    "twitch.tv",
    "khanacademy.org",
    "theguardian.com",
    "paypal.com",
    "spotify.com",
    "att.com",
    "nfl.com",
    "realtor.com",
    "ca.gov",
    "goodreads.com",
    "office.com",
    "ufl.edu",
    "mlb.com",
    "foodnetwork.com",
    "bbc.com",
    "apartments.com",
    "npr.org",
    "wowhead.com", ]
fortune500 = ["walmart.com",
              "exxonmobil.com",
              "berkshirehathaway.com",
              "apple.com",
              "unitedhealthgroup.com",
              "mckesson.com",
              "cvshealth.com",
              "amazon.com",
              "att.com",
              "gm.com",
              "ford.com",
              "amerisourcebergen.com",
              "chevron.com",
              "cardinalhealth.com",
              "costco.com",
              "verizon.com",
              "kroger.com",
              "ge.com",
              "walgreensbootsalliance.com",
              "jpmorganchase.com",
              "fanniemae.com",
              "abc.xyz",
              "homedepot.com",
              "bankofamerica.com",
              "express-scripts.com",
              "wellsfargo.com",
              "boeing.com",
              "phillips66.com",
              "antheminc.com",
              "microsoft.com",
              "valero.com",
              "citigroup.com",
              "comcastcorporation.com",
              "ibm.com",
              "delltechnologies.com",
              "statefarm.com",
              "jnj.com",
              "freddiemac.com",
              "target.com",
              "lowes.com",
              "marathonpetroleum.com",
              "pg.com",
              "metlife.com",
              "ups.com",
              "pepsico.com",
              "intel.com",
              "dow-dupont.com",
              "adm.com",
              "aetna.com",
              "fedex.com",
              "utc.com",
              "prudential.com",
              "albertsons.com",
              "sysco.com",
              "disney.com",
              "humana.com",
              "pfizer.com",
              "hp.com",
              "lockheedmartin.com",
              "aig.com",
              "centene.com",
              "cisco.com",
              "hcahealthcare.com",
              "energytransfer.com",
              "caterpillar.com",
              "nationwide.com",
              "morganstanley.com",
              "libertymutual.com",
              "newyorklife.com",
              "gs.com",
              "aa.com",
              "bestbuy.com",
              "cigna.com",
              "charter.com",
              "delta.com",
              "facebook.com",
              "honeywell.com",
              "merck.com",
              "allstate.com",
              "tysonfoods.com",
              "united.com",
              "oracle.com",
              "techdata.com",
              "tiaa.org",
              "tjx.com",
              "americanexpress.com",
              "coca-colacompany.com",
              "publix.com",
              "nike.com",
              "andeavor.com",
              "wfscorp.com",
              "exeloncorp.com",
              "massmutual.com",
              "riteaid.com",
              "conocophillips.com",
              "chsinc.com",
              "3m.com",
              "timewarner.com",
              "generaldynamics.com",
              "usaa.com",
              "capitalone.com",
              "johndeere.com",
              "intlfcstone.com",
              "northwesternmutual.com",
              "enterpriseproducts.com",
              "travelers.com",
              "hpe.com",
              "pmi.com",
              "21cf.com",
              "abbvie.com",
              "abbott.com",
              "progressive.com",
              "arrow.com",
              "kraftheinzcompany.com",
              "plainsallamerican.com",
              "gilead.com",
              "mondelezinternational.com",
              "northropgrumman.com",
              "raytheon.com",
              "macysinc.com",
              "usfoods.com",
              "usbank.com",
              "dollargeneral.com",
              "internationalpaper.com",
              "duke-energy.com",
              "southerncompany.com",
              "marriott.com",
              "avnet.com",
              "lilly.com",
              "amgen.com",
              "aboutmcdonalds.com",
              "starbucks.com",
              "qualcomm.com",
              "dollartree.com",
              "pbfenergy.com",
              "ielp.com",
              "aflac.com",
              "autonation.com",
              "penskeautomotive.com",
              "whirlpoolcorp.com",
              "up.com",
              "southwest.com",
              "manpowergroup.com",
              "thermofisher.com",
              "bms.com",
              "halliburton.com",
              "tenethealth.com",
              "lear.com",
              "cummins.com",
              "micron.com",
              "nucor.com",
              "molinahealthcare.com",
              "fluor.com",
              "altria.com",
              "paccar.com",
              "thehartford.com",
              "kohls.com",
              "wdc.com",
              "jabil.com",
              "chs.net",
              "visa.com",
              "danaher.com",
              "kimberly-clark.com",
              "aecom.com",
              "pnc.com",
              "centurylink.com",
              "nexteraenergy.com",
              "pgecorp.com",
              "synnex.com",
              "wellcare.com",
              "pfgc.com",
              "searsholdings.com",
              "synchronyfinancial.com",
              "carmax.com",
              "bnymellon.com",
              "fcx.com",
              "genpt.com",
              "emerson.com",
              "davita.com",
              "supervalu.com",
              "gapinc.com",
              "generalmills.com",
              "nordstrom.com",
              "colgatepalmolive.com",
              "aep.com",
              "xpo.com",
              "goodyear.com",
              "omnicomgroup.com",
              "cdw.com",
              "sherwin.com",
              "ppg.com",
              "ti.com",
              "chrobinson.com",
              "westrock.com",
              "cognizant.com",
              "newellbrands.com",
              "cbscorporation.com",
              "evhc.net",
              "monsanto.com",
              "aramark.com",
              "appliedmaterials.com",
              "wm.com",
              "dish.com",
              "itw.com",
              "lfg.com",
              "hollyfrontier.com",
              "cbre.com",
              "textron.com",
              "rossstores.com",
              "principal.com",
              "drhorton.com",
              "mmc.com",
              "devonenergy.com",
              "aes.com",
              "ecolab.com",
              "landolakesinc.com",
              "loews.com",
              "kindermorgan.com",
              "firstenergycorp.com",
              "oxy.com",
              "viacom.com",
              "paypal.com",
              "nglenergypartners.com",
              "celgene.com",
              "arconic.com",
              "kelloggcompany.com",
              "sands.com",
              "stanleyblackanddecker.com",
              "bookingholdings.com",
              "lennar.com",
              "lb.com",
              "dteenergy.com",
              "dominionenergy.com",
              "rgare.com",
              "jcpenney.com",
              "mastercard.com",
              "blackrock.com",
              "henryschein.com",
              "guardianlife.com",
              "stryker.com",
              "jefferies.com",
              "vfc.com",
              "adp.com",
              "edisoninvestor.com",
              "biogen.com",
              "ussteel.com",
              "core-mark.com",
              "bedbathandbeyond.com",
              "oneok.com",
              "bbt.com",
              "bd.com",
              "ameriprise.com",
              "farmers.com",
              "firstdata.com",
              "conedison.com",
              "parker.com",
              "anadarko.com",
              "elcompanies.com",
              "statestreet.com",
              "tesla.com",
              "netflix.com",
              "alcoa.com",
              "discover.com",
              "praxair.com",
              "csx.com",
              "xcelenergy.com",
              "unum.com",
              "uhsinc.com",
              "nrg.com",
              "eogresources.com",
              "sempra.com",
              "toysrusinc.com",
              "group1auto.com",
              "entergy.com",
              "molsoncoors.com",
              "l3t.com",
              "ball.com",
              "autozone.com",
              "murphyusa.com",
              "mgmresorts.com",
              "officedepot.com",
              "huntsman.com",
              "baxter.com",
              "norfolksouthern.com",
              "salesforce.com",
              "labcorp.com",
              "grainger.com",
              "libertyinteractive.com",
              "autoliv.com",
              "livenationentertainment.com",
              "xerox.com",
              "leidos.com",
              "corning.com",
              "lithiainvestorrelations.com",
              "expediagroup.com",
              "republicservices.com",
              "jacobs.com",
              "sonicautomotive.com",
              "ally.com",
              "lkqcorp.com",
              "borgwarner.com",
              "fnf.com",
              "suntrust.com",
              "iqvia.com",
              "rsac.com",
              "nvidia.com",
              "voya.com",
              "centerpointenergy.com",
              "ebay.com",
              "eastman.com",
              "amfam.com",
              "steeldynamics.com",
              "pacificlife.com",
              "chk.com",
              "mohawkind.com",
              "quantaservices.com",
              "advanceautoparts.com",
              "owens-minor.com",
              "unfi.com",
              "tenneco.com",
              "conagrabrands.com",
              "gamestop.com",
              "hormelfoods.com",
              "hiltonworldwide.com",
              "frontier.com",
              "fisglobal.com",
              "pseg.com",
              "bostonscientific.com",
              "oreillyauto.com",
              "aboutschwab.com",
              "globalp.com",
              "pvh.com",
              "avisbudgetgroup.com",
              "targaresources.com",
              "hertz.com",
              "calpine.com",
              "mutualofomaha.com",
              "crowncork.com",
              "kiewit.com",
              "dicks.com",
              "pultegroupinc.com",
              "navistar.com",
              "thrivent.com",
              "dcpmidstream.com",
              "airproducts.com",
              "veritivcorp.com",
              "agcocorp.com",
              "genworth.com",
              "univar.com",
              "newscorp.com",
              "spartannash.com",
              "westlake.com",
              "williams.com",
              "lamresearch.com",
              "alaskaair.com",
              "jll.com",
              "anixter.com",
              "campbellsoupcompany.com",
              "interpublic.com",
              "dovercorporation.com",
              "zimmerbiomet.com",
              "deanfoods.com",
              "footlocker-inc.com",
              "eversource.com",
              "alliancedata.com",
              "53.com",
              "questdiagnostics.com",
              "emcorgroup.com",
              "wrberkley.com",
              "wesco.com",
              "coty.com",
              "wecenergygroup.com",
              "masco.com",
              "dxc.technology",
              "auto-owners.com",
              "edwardjones.com",
              "libertymedia.com",
              "erieinsurance.com",
              "thehersheycompany.com",
              "pplweb.com",
              "huntingtoningalls.com",
              "mosaicco.com",
              "jmsmucker.com",
              "delekus.com",
              "newmont.com",
              "cbrands.com",
              "ryder.com",
              "nov.com",
              "adobe.com",
              "lifepointhealth.net",
              "tractorsupply.com",
              "thorindustries.com",
              "dana.com",
              "weyerhaeuser.com",
              "jbhunt.com",
              "darden.com",
              "yumchina.com",
              "blackstone.com",
              "berryglobal.com",
              "bldr.com",
              "activisionblizzard.com",
              "jetblue.com",
              "amphenol.com",
              "amark.com",
              "spiritaero.com",
              "rrdonnelley.com",
              "harris.com",
              "expeditors.com",
              "discovery.com",
              "o-i.com",
              "sanmina.com",
              "key.com",
              "afginc.com",
              "oshkoshcorporation.com",
              "rockwellcollins.com",
              "kindredhealthcare.com",
              "insight.com",
              "drpeppersnapplegroup.com",
              "americantower.com",
              "fortive.com",
              "ralphlauren.com",
              "spectrumbrands.com",
              "ascenaretail.com",
              "unitedrentals.com",
              "caseys.com",
              "graybar.com",
              "averydennison.com",
              "mastec.com",
              "cmsenergy.com",
              "hdsupply.com",
              "raymondjames.com",
              "ncr.com",
              "hanes.com",
              "asburyauto.com",
              "citizensbank.com",
              "packagingcorp.com",
              "alleghany.com",
              "apachecorp.com",
              "dillards.com",
              "assurant.com",
              "franklinresources.com",
              "owenscorning.com",
              "motorolasolutions.com",
              "nvrinc.com",
              "rockwellautomation.com",
              "treehousefoods.com",
              "wynnresorts.com",
              "olin.com",
              "aam.com",
              "oldrepublic.com",
              "chemours.com",
              "iheartmedia.com",
              "ameren.com",
              "ajg.com",
              "celanese.com",
              "sealedair.com",
              "ugicorp.com",
              "realogy.com",
              "burlington.com",
              "regions.com",
              "aksteel.com",
              "securian.com",
              "spglobal.com",
              "markelcorp.com",
              "ta-petro.com",
              "conduent.com",
              "mtb.com",
              "thecloroxcompany.com",
              "amtrustfinancial.com",
              "kkr.com",
              "ulta.com",
              "yum.com",
              "regeneron.com",
              "windstream.com",
              "magellanhealth.com",
              "westernsouthern.com",
              "theice.com",
              "ingredion.com",
              "wyndhamdestinations.com",
              "tollbrothers.com",
              "seaboardcorp.com",
              "boozallen.com",
              "firstam.com",
              "cinfin.com",
              "avoninvestor.com",
              "northerntrust.com",
              "fiserv.com",
              "harley-davidson.com",
              "cheniere.com",
              "pattersoncompanies.com",
              "peabodyenergy.com",
              "onsemi.com",
              "simon.com",
              "westernunion.com",
              "netapp.com",
              "polaris.com",
              "pxd.com",
              "abm.com",
              "vistraenergy.com",
              "cintas.com"]

import subprocess

import tldextract

results = {}
import json
from queue import Queue

from threading import Thread


class Worker(Thread):
    """ Thread executing tasks from a given tasks queue """

    def __init__(self, tasks):
        Thread.__init__(self)
        self.tasks = tasks
        self.daemon = True
        self.start()

    def run(self):
        while True:
            func, args, kargs = self.tasks.get()
            try:
                func(*args, **kargs)
            except Exception as e:
                # An exception happened in this thread
                print(e)
            finally:
                # Mark this task as done, whether an exception happened or not
                self.tasks.task_done()


class ThreadPool:
    """ Pool of threads consuming tasks from a queue """

    def __init__(self, num_threads):
        self.tasks = Queue(num_threads)
        for _ in range(num_threads):
            Worker(self.tasks)

    def add_task(self, func, *args, **kargs):
        """ Add a task to the queue """
        self.tasks.put((func, args, kargs))

    def map(self, func, args_list):
        """ Add a list of tasks to the queue """
        for args in args_list:
            self.add_task(func, args)

    def wait_completion(self):
        """ Wait for completion of all the tasks in the queue """
        self.tasks.join()


import threading

lock = threading.Lock()


def save(out):
    lock.acquire()
    with open('fortune.json', 'w') as file:
        file.write(json.dumps(out))
        file.close()
        lock.release()


# for domain in top100:
#     pure_domain = checkdmarc.get_base_domain(domain)
#     dmarc = {}
#     try:
#         dmarc = checkdmarc.get_dmarc_record(pure_domain, timeout=10.0)
#     except Exception as e:
#         print('Error with ' + domain)
#         print(e)
#     try:
#         spf = checkdmarc.get_spf_record(pure_domain, timeout=10.0, )
#         results[domain] = {'dmarc': dmarc, 'spf': spf}
#         save(results)
#     except Exception as e:
#         print('Error with ' + domain)
#         print(e)
#     print(domain)
def check_records(domain):
    cmd = "checkdmarc " + domain
    ps = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output = str(ps.communicate()[0].decode('utf-8'))
    print(domain)
    results[domain] = output
    save(results)


values = []

for domain in fortune500:
    url = tldextract.extract(domain)
    values.append(url.domain + '.' + url.suffix)

pool = ThreadPool(5)

pool.map(check_records, values)
pool.wait_completion()
